### ISSUE TITLE
RuntimeError: expected device cpu but got device cuda:0

### ISSUE THREAD

**Issue by gerkulesov** [signatrix/efficientdet#26]
I am trying to run your pretrained model on CPU.

I replace
`model = torch.load(opt.pretrained_model).module`
with
`model = torch.load(opt.pretrained_model, map_location='cpu').module`

And comment al lines about access to cuda.

After running test script I got title error:
```
Traceback (most recent call last):
  File "DEMO.py", line 112, in <module>
    test(opt)
  File "DEMO.py", line 77, in test
    scores, labels, boxes = model(new_image)
  File "/home/gerkulesovr/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerkulesovr/Projects/Detectors/efficientdet/src/model.py", line 275, in forward
    transformed_anchors = self.regressBoxes(anchors, regression)
  File "/home/gerkulesovr/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerkulesovr/Projects/Detectors/efficientdet/src/utils.py", line 34, in forward
    pred_ctr_x = ctr_x + dx * widths
RuntimeError: expected device cpu but got device cuda:0
```
Could you help me?

**Comment by gerkulesov** [comment]
Sorry, I am totally fool :)
At my machine `torch.cuda.is_available()` is always true, so in utils.py makes variables in GPU mode.

It was needed to comment
```
if torch.cuda.is_available():
    self.mean = self.mean.cuda()
    self.std = self.std.cuda()
```
and
```
if torch.cuda.is_available():
    anchors = anchors.cuda()
```
in utils.py
