### ISSUE TITLE
Continue training from pre-saved model

### ISSUE THREAD

**Issue by mitulsaha** [signatrix/efficientdet#31]
Hi,

How do I continue training by loading a pre-saved model?

Thanks!

**Comment by mitulsaha** [comment]
My training has actually crashed after 8 epochs:-

Epoch: 8/500. Classification loss: 0.16313. Regression loss: 0.26183. Total loss: 0.42496
/home/local/YORK/mitul.saha/software/anaconda3/envs/venv_conda_pt1.4/lib/python3.8/site-packages/torch/onnx/symbolic_helper.
py:245: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cau
se results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transfo
rm the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and ne
arest_mode).
We recommend using opset 11 and above for models using this operator. 
  warnings.warn("You are trying to export the model with " + onnx_op + " for ONNX opset version "
/home/local/YORK/mitul.saha/software/anaconda3/envs/venv_conda_pt1.4/lib/python3.8/site-packages/torch/onnx/utils.py:722: Us
erWarning: ONNX export failed on an operator with unrecognized namespace torchvision::nms; If you are trying to export a cus
tom operator, make sure you registered it with the right domain and version.Otherwise please report a bug
  warnings.warn("ONNX export failed on an operator with unrecognized namespace {}::{}; "
Traceback (most recent call last):
  File "train.COCO_10Labels.py", line 218, in <module>
    train(opt)
  File "train.COCO_10Labels.py", line 197, in train
    torch.onnx.export(model.module, dummy_input,
  File "/home/local/YORK/mitul.saha/software/anaconda3/envs/venv_conda_pt1.4/lib/python3.8/site-packages/torch/onnx/__init__
.py", line 144, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/local/YORK/mitul.saha/software/anaconda3/envs/venv_conda_pt1.4/lib/python3.8/site-packages/torch/onnx/utils.py
", line 62, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/local/YORK/mitul.saha/software/anaconda3/envs/venv_conda_pt1.4/lib/python3.8/site-packages/torch/onnx/utils.py
", line 426, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export operator torchvision::nms

**Comment by nassarofficial** [comment]
same problem, did u find a solution?

**Comment by mitulsaha** [comment]
No solution yet ... someone help please :D

**Comment by mitulsaha** [comment]
BTW, temporary hack for ONNX export crash:- Just turn off the ONNX export for now, till a solution is found.

**Comment by nassarofficial** [comment]
I think I found a fix. Just add "opset_version=11", worked for me.

>                     torch.onnx.export(model, dummy_input,
>                                       os.path.join(opt.saved_path, "signatrix_efficientdet_coco.onnx"),
>                                       verbose=False,opset_version=11)
>

**Comment by mitulsaha** [comment]
Thanks @nassarofficial! I actually created a new issue for this https://github.com/signatrix/efficientdet/issues/33, as this issue was originally supposed to be for "how to continue training ..."
