### ISSUE TITLE
The size of tensor a (11) must match the size of tensor b (12) at non-singleton dimension 3

### ISSUE THREAD

**Issue by haibochina** [signatrix/efficientdet#8]
I just use the efficientdet as backbone of FCOS, but there is something wrong in bifpn. When you construct your bifpn model did you met this kind of error?
the sizes always do not match!

  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/backbone/efficientdet.py", line 89, in forward
    p5_up = self.conv5_up(weight[0] * p5_in + weight[1] * self.p5_upsample(p6_up))
RuntimeError: The size of tensor a (11) must match the size of tensor b (12) at non-singleton dimension 3

**Comment by uvipen** [comment]
Could you provide more information? What is your input size ?

**Comment by haibochina** [comment]
I have changed the input size as your code, here is the code of mine.

class Resize(object):
    def __init__(self, min_size, max_size):
        if not isinstance(min_size, (list, tuple)):
            min_size = (min_size,)
        self.min_size = min_size
        self.max_size = max_size

    # modified from torchvision to add support for max size
    def get_size(self, image_size):
#         w, h = image_size
#         size = random.choice(self.min_size)
#         max_size = self.max_size
#         if max_size is not None:
#             min_original_size = float(min((w, h)))
#             max_original_size = float(max((w, h)))
#             if max_original_size / min_original_size * size > max_size:
#                 size = int(round(max_size * min_original_size / max_original_size))

#         if (w <= h and w == size) or (h <= w and h == size):
#             return (h, w)

#         if w < h:
#             ow = size
#             oh = int(size * h / w)
#         else:
#             oh = size
#             ow = int(size * w / h)

#         return (oh, ow)
        width, height = image_size
        common_size = 512
        if height > width:
            scale = common_size / height
            resized_height = common_size
            resized_width = int(width * scale)
        else:
            scale = common_size / width
            resized_height = int(height * scale)
            resized_width = common_size
        return (resized_height, resized_width)

    def __call__(self, image, target=None):
        size = self.get_size(image.size)
        image = F.resize(image, size)
        if isinstance(target, list):
            target = [t.resize(image.size) for t in target]
        elif target is None:
            return image
        else:
            target = target.resize(image.size)
        return image, target

**Comment by haibochina** [comment]
I have changed the input size the same as your code,
`class Resize(object):
    def __init__(self, min_size, max_size):
        if not isinstance(min_size, (list, tuple)):
            min_size = (min_size,)
        self.min_size = min_size
        self.max_size = max_size

    # modified from torchvision to add support for max size
    def get_size(self, image_size):
#         w, h = image_size
#         size = random.choice(self.min_size)
#         max_size = self.max_size
#         if max_size is not None:
#             min_original_size = float(min((w, h)))
#             max_original_size = float(max((w, h)))
#             if max_original_size / min_original_size * size > max_size:
#                 size = int(round(max_size * min_original_size / max_original_size))

#         if (w <= h and w == size) or (h <= w and h == size):
#             return (h, w)

#         if w < h:
#             ow = size
#             oh = int(size * h / w)
#         else:
#             oh = size
#             ow = int(size * w / h)

#         return (oh, ow)
        width, height = image_size
        common_size = 512
        if height > width:
            scale = common_size / height
            resized_height = common_size
            resized_width = int(width * scale)
        else:
            scale = common_size / width
            resized_height = int(height * scale)
            resized_width = common_size
        return (resized_height, resized_width)

    def __call__(self, image, target=None):
        size = self.get_size(image.size)
        image = F.resize(image, size)
        if isinstance(target, list):
            target = [t.resize(image.size) for t in target]
        elif target is None:
            return image
        else:
            target = target.resize(image.size)
        return image, target
`

**Comment by haibochina** [comment]
I have changed the input size the same as your code 
`class Resize(object):
    def __init__(self, min_size, max_size):
        if not isinstance(min_size, (list, tuple)):
            min_size = (min_size,)
        self.min_size = min_size
        self.max_size = max_size

    # modified from torchvision to add support for max size
    def get_size(self, image_size):
#         w, h = image_size
#         size = random.choice(self.min_size)
#         max_size = self.max_size
#         if max_size is not None:
#             min_original_size = float(min((w, h)))
#             max_original_size = float(max((w, h)))
#             if max_original_size / min_original_size * size > max_size:
#                 size = int(round(max_size * min_original_size / max_original_size))

#         if (w <= h and w == size) or (h <= w and h == size):
#             return (h, w)

#         if w < h:
#             ow = size
#             oh = int(size * h / w)
#         else:
#             oh = size
#             ow = int(size * w / h)

#         return (oh, ow)
        width, height = image_size
        common_size = 512
        if height > width:
            scale = common_size / height
            resized_height = common_size
            resized_width = int(width * scale)
        else:
            scale = common_size / width
            resized_height = int(height * scale)
            resized_width = common_size
        return (resized_height, resized_width)

    def __call__(self, image, target=None):
        size = self.get_size(image.size)
        image = F.resize(image, size)
        if isinstance(target, list):
            target = [t.resize(image.size) for t in target]
        elif target is None:
            return image
        else:
            target = target.resize(image.size)
        return image, target
`

**Comment by haibochina** [comment]
I have changed the input size the same as your code, maximun=512

**Comment by haibochina** [comment]
I print the input shape, is it true?

index created!
2020-01-09 01:26:45,568 fcos_core.trainer INFO: Start training
torch.Size([1, 3, 320, 512])
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "tools/train_net.py", line 181, in <module>
    main()
  File "tools/train_net.py", line 174, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 80, in train
    arguments,
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/engine/trainer.py", line 69, in do_train
    loss_dict = model(images, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/backbone/efficientdet.py", line 217, in forward
    features = self.bifpn(features)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/backbone/efficientdet.py", line 82, in forward
    p6_up = self.conv6_up(weight[0] * p6_in + weight[1] * self.p6_upsample(p7_in))
RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 2

**Comment by uvipen** [comment]
Hi,
I see the point here. EfficientDet D0 accept input of size 512x512, but based on the log you provide, your input size is 320x512.
Bests,

**Comment by abhigoku10** [comment]
@uvipen i tried to integrate BIFPN with resnet backbone for i am getting the same error " RunTimeError: the size of tensor a (9) must match the size of tensor b (10) at  non -singleton  dimension 3 .. is this issue related to the input size also ??

**Comment by haibochina** [comment]
@uvipen ，Thankyou!

**Comment by abhigoku10** [comment]
@haibochina  can you share your efficientdet with FCOS code , so that i can run itat my end
